### ISSUE TITLE
improve installDependencies

### ISSUE THREAD

**Issue by csacro** [SoPra-Team-17/LibClient#14]
könnte man hier stattdessen einfach `./external/LibCommon/installDependencies.sh` aufrufen?

_Originally posted by @ottojo in https://github.com/SoPra-Team-17/LibClient/pull/9/threads/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjU0Mzg2MzA2OnYy/unresolve_

Aus irgendwelchen Gründen wird beim builden `./external/LibCommon/installDependencies.sh` nicht gefunden.

**Comment by ottojo** [comment]
geht wohl beim server https://github.com/SoPra-Team-17/Server/blob/develop/installDependencies.sh#L8

**Comment by csacro** [comment]
Keine Ahnung wieso das nicht ging. Jetzt geht es: #9
