### ISSUE TITLE
improve submodule (LibCommon) include

### ISSUE THREAD

**Issue by csacro** [SoPra-Team-17/LibClient#15]
```suggestion
add_subdirectory(extern/LibCommon)
```
Das muss auch so möglich sein. Siehe https://github.com/ottojo/LibCommonTest/blob/master/CMakeLists.txt

_Originally posted by @ottojo in https://github.com/SoPra-Team-17/LibClient/pull/9_

Es treten Konflikte auf, da sowohl LibCommon als auch LibClient googletest über cmake einbinden

**Comment by ottojo** [comment]
Mit https://github.com/SoPra-Team-17/LibCommon/pull/64 und `if (NOT TARGET gtest)` um die gtest installation und einem eindeutigen Namen für die test executable (nicht `allTests`) ist das gefixt

**Comment by csacro** [comment]
bereits in #9 mit https://github.com/SoPra-Team-17/Server/blob/develop/CMakeLists.txt#L35-L36 gefixt

**Comment by ottojo** [comment]
Ist mehr so ein workaround, würde das gerne properly fixen und nicht nur die tests ausschalten :D

**Comment by csacro** [comment]
waiting for [LibCommon#69](https://github.com/SoPra-Team-17/LibCommon/pull/69) to be approved
