### ISSUE TITLE
Disconnect on gameLeave

### ISSUE THREAD

**Issue by Marco5de** [SoPra-Team-17/LibClient#56]

**Comment by csacro** [comment]
Nach einer GameLeave message bestätigt der Server das Verlassen mit einer GamerLeft message (siehe Standard).
Da aber generell nichts dagegen spricht, dass man im Network-State "GAME_OVER" `connect(...)` aufruft, um sich mit  einem beliebigen Server zu verbinden, habe ich das gemacht.
(D.h. der Client kann sich über `connect(...)`  neu verbinden, nachdem er eine Verlassensbestätigung bekommen hat.)
